name: Generate Commits, PRs & Issues

on:
  workflow_dispatch:
    inputs:
      total_commits:
        description: "Jumlah total commit"
        required: true
        default: "1650"
      total_days:
        description: "Jumlah hari pembagian commit"
        required: true
        default: "365"
      total_prs:
        description: "Jumlah Pull Request"
        required: true
        default: "1"
      total_issues:
        description: "Jumlah Issue"
        required: true
        default: "1"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git identity
        run: |
          git config user.name "rgmauer"
          git config user.email "15880189+rgmauer@users.noreply.github.com"

      - name: Generate distributed commits
        env:
          TOTAL_COMMITS: ${{ github.event.inputs.total_commits }}
          TOTAL_DAYS: ${{ github.event.inputs.total_days }}
        run: |
          mkdir -p logs
          git pull origin main || true
          COMMITS_PER_DAY=$((TOTAL_COMMITS / TOTAL_DAYS))
          START_DATE=$(date -d "$TOTAL_DAYS days ago" +%Y-%m-%d)

          echo "Membuat $TOTAL_COMMITS commit selama $TOTAL_DAYS hari..."
          for ((day=0; day<TOTAL_DAYS; day++)); do
            commit_date=$(date -d "$START_DATE +$day days" +%Y-%m-%d)
            for ((i=1; i<=COMMITS_PER_DAY; i++)); do
              echo "Commit ke-$i pada $commit_date" >> logs/commit_$day.txt
              git add logs/commit_$day.txt
              GIT_COMMITTER_DATE="$commit_date 12:00:00" \
              GIT_AUTHOR_DATE="$commit_date 12:00:00" \
              git commit -m "Commit $i on $commit_date" || true
            done
          done

          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }} HEAD:main
